# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Advisors
    url: info-advisors
    weight: 10
  - name: Students
    url: info-students
    weight: 11
  - id: Semesters
    name: Semesters
    url: projects
    weight: 12
  # - name: Projects
  #   url: projects
  #   weight: 10
  - name: People
    url: people
    weight: 20
  - name: Events
    url: event
    weight: 40
  # - name: Publications
  #   url: publication
  #   weight: 50
  - name: Contact
    url: contact
    weight: 60
  - !!python/object:datafest_archive.templates.models.MenuItem
    name: Fall 2023
    parent: Semesters
    url: editions/2023-fall
    weight: 1
  - !!python/object:datafest_archive.templates.models.MenuItem
    name: Spring 2023
    parent: Semesters
    url: editions/2023-spring
    weight: 2
  ## People per semester
  - !!python/object:datafest_archive.templates.models.MenuItem
    name: Fall 2022
    parent: People
    url: editions/2022-fall
    weight: 3
