!Menu
main:
  - name: Home
    url: /
    weight: 1
  - name: Advisors
    url: info-advisors
    weight: 10
  - name: Students
    url: info-students
    weight: 20
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Semesters
    parent: null
    url: previous-semesters
    weight: 30
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Contact
    parent: null
    url: contact
    weight: 40
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Fall 2023 (Open)
    parent: Semesters
    url: editions/2023-fall
    weight: 10
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Spring 2023
    parent: Semesters
    url: editions/2023-spring
    weight: 20
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: 2019 to 2022
    parent: Semesters
    url: https://sites.usc.edu/ckids/datafest-s22-spring-2022/
    weight: 21
