!Menu
main:
  - name: Home
    url: /
    weight: 1
  - name: Advisors
    url: info-advisors
    weight: 10
  - name: Students
    url: info-students
    weight: 20
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Semesters
    parent: null
    url: previous-semesters
    weight: 30
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Contact
    parent: null
    url: contact
    weight: 40
  - name: Fall 2023 (Open)
    parent: Semesters
    url: editions/2023-fall
    weight: 10
  - name: Spring 2023
    parent: Semesters
    url: editions/2023-spring
    weight: 20
  - name: Fall 2022
    parent: Semesters
    url: editions/2022-fall
    weight: 30
  - name: Spring 2022
    parent: Semesters
    url: editions/2022-spring
    weight: 40
  - name: Fall 2021
    parent: Semesters
    url: editions/2021-fall
    weight: 50
  - name: Spring 2021
    parent: Semesters
    url: editions/2021-spring
    weight: 60
  - name: Fall 2020
    parent: Semesters
    url: editions/2020-fall
    weight: 70
  - name: Spring 2020
    parent: Semesters
    url: editions/2020-spring
    weight: 80
  - name: Fall 2019
    parent: Semesters
    url: editions/2019-fall
    weight: 90
  - name: Spring 2019
    parent: Semesters
    url: editions/2019-spring
    weight: 100
