!Menu
main:
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Information
    parent: null
    url: info-advisors
    weight: 1
  # - !!python/object:datafest_archive.models.website.configuration.MenuItem
  #   name: Info for Students
  #   parent: null
  #   url: info-students
  #   weight: 2
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Previous Semesters
    parent: null
    url: previous-semesters
    weight: 3
  # - !!python/object:datafest_archive.models.website.configuration.MenuItem
  #   name: People
  #   parent: null
  #   url: people
  #   weight: 4
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Contact
    parent: null
    url: contact
    weight: 6
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: Spring 2023
    parent: Previous Semesters
    url: editions/2023-spring
    weight: 20
  - !!python/object:datafest_archive.models.website.configuration.MenuItem
    name: 2019 to 2022
    parent: Previous Semesters
    url: https://sites.usc.edu/ckids/datafest-s22-spring-2022/
    weight: 21
