main:
  - name: Home
    url: /
    weight: 1

  - name: Projects
    url: all-projects/
    weight: 9

  - name: Advisors
    url: /info-advisors
    weight: 10

  - name: Students
    url: /info-students
    weight: 15

  - name: Resources
    title: Resources
    url: materials/resources-timeless
    weight: 16

  - name: Spring 2024
    url: calls/2024-spring/advisors
    weight: 20

  - name: Call for Advisors
    parent: Spring 2024
    url: calls/2024-spring/advisors

  - name: Info for Students
    parent: Spring 2024
    url: calls/2024-spring/students

  - name: Fall 2023
    url: editions/2023-fall
    weight: 22

  - name: Dates
    parent: Fall 2023
    url: editions/2023-fall/#dates
    weight: 10

  - name: Resources (Fall 2023)
    parent: Fall 2023
    url: editions/2023-fall/#2-resources-students
    weight: 20

  - name: DataFirst Lab
    parent: Fall 2023
    url: materials/2023-fall/datafirst-lab-at-isi/
    weight: 30

  - name: Tutorials
    parent: Fall 2023
    url: materials/2023-fall/tutorials
    weight: 30

  - name: Semesters
    parent: null
    url: previous-semesters
    weight: 30
  - name: Contact
    parent: null
    url: contact
    weight: 40
  - name: Fall 2023 (Open)
    parent: Semesters
    url: editions/2023-fall
    weight: 10
  - name: Spring 2023
    parent: Semesters
    url: editions/2023-spring
    weight: 20
  - name: Fall 2022
    parent: Semesters
    url: editions/2022-fall
    weight: 30
  - name: Spring 2022
    parent: Semesters
    url: editions/2022-spring
    weight: 40
  - name: Fall 2021
    parent: Semesters
    url: editions/2021-fall
    weight: 50
  - name: Spring 2021
    parent: Semesters
    url: editions/2021-spring
    weight: 60
  - name: Fall 2020
    parent: Semesters
    url: editions/2020-fall
    weight: 70
  - name: Spring 2020
    parent: Semesters
    url: editions/2020-spring
    weight: 80
  - name: Fall 2019
    parent: Semesters
    url: editions/2019-fall
    weight: 90
  - name: Spring 2019
    parent: Semesters
    url: editions/2019-spring
    weight: 100
  - name: Explore all projects
    parent: Semesters
    url: all-projects
    weight: 1000
